# Generated by Django 5.1.1 on 2024-10-19 08:19

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=customers.models.upload_path),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
